### ISSUE TITLE
Filter away results with no stock

### ISSUE THREAD

**Issue by piprett** [PatriikPlays/findshop#19]

**Comment by PatriikPlays** [comment]
IMO keeping them is nicer. Currently, they just get pushed to the back of the results.

**Comment by piprett** [comment]
https://github.com/Pixium/findshop/blob/2f6618338186591780120f4c27f4632cec0753d2/src/chatboxHandler.ts#L162-L171

LGTM, should probably replace `let` with `const`, but no big deal
